#######################################################################################################################
# Upsun demo project configuration
#######################################################################################################################
# Application configuration.
applications:    
    # App 1: Frontend (JS)
    frontend:

        source:
            root: "frontend"

        #type: "nodejs:18"
        stack: ['nodejs@18']

        #build:
        #    flavor: none

        hooks:
            build: |
                set -e
                npm install
                export REACT_APP_BACKEND_URL="/"
                export REACT_APP_PROJECT_ID=$PLATFORM_PROJECT
                npm run build

        relationships:
           api: "backend:http"

        web:
            locations:
                /:
                    root: build
                    index:
                        - index.html
                    expires: 2m
                    scripts: false
                    allow: true
                    rules:
                        static\/*:
                            expires: 365d

    # App 2: Backend (Python)
    backend:

        source:
            root: "backend"

        #type: "python:3.11"
        stack: ["python@3.11", "ruby@3.1", "php@8.1"]

        #build:
        #    flavor: none
        hooks:
            build: |
                set -eux
                #pip install --upgrade pip
                pip install -r requirements.txt
                
        web:
            commands:
                start: "gunicorn main:app"
            upstream:
                socket_family: tcp
            locations:
                /:
                    passthru: true

    php:
      source:
        root: "php"

      stack:
        - "php@8.2":
          extensions:
            - ctype
            - iconv
            - apcu
            - mbstring
            - sodium
            - xsl
            - pdo_pgsql
          disabled_extensions:
            - sqlite3
          max_execution_time: 300
          memory_limit: 256M

        - "nodejs@20"
        - "python@3.10"
        - imagemagick

      # The web key configures the web server running in front of your app.
      # More information: https://docs.platform.sh/create-apps/app-reference.html#web
      web:
        commands:
          start: "php-fpm -c /etc/php/8.2/fpm/php.ini -y /etc/php/8.2/fpm/php-fpm.conf"
        # Each key in locations is a path on your site with a leading /.
        # More information: https://docs.platform.sh/create-apps/app-reference.html#locations
        locations:
          "/":
            # The directory to serve static assets for this location relative to the app’s root directory. Must be an
            # actual directory inside the root directory.
            root: ""
            # Whether to forward disallowed and missing resources from this location to the app. A string is a path
            # with a leading / to the controller, such as /index.php.
            passthru: '/index.php'
            # Files to consider when serving a request for a directory.
            index:
              - index.php
            # Whether to allow scripts to run. Doesn’t apply to paths specified in passthru. Meaningful only on PHP containers.
            scripts: true
            # Whether to allow serving files which don’t match a rule.
            allow: true
            headers:
              Access-Control-Allow-Origin: "*"

# #add_service_start
# ######################################################################################################################
# # Step 3: Add a service. Uncomment this section.
# ######################################################################################################################
#         relationships:
#             redis_session: "redis_service:redis"

# services:
#     redis_service:
#         type: "redis:7.0"
# ######################################################################################################################
# #add_service_end
    
# Routes configuration.
routes:
    "https://{default}/":
        id: frontend
        type: upstream
        primary: true
        upstream: "frontend:http"

    "https://www.{default}":
        id: frontend-redirect
        type: redirect
        to: "https://{default}/"

    "https://{default}/api/":
        id: backend
        type: upstream
        upstream: "backend:http"

    "https://php.{default}/":
        id: php
        type: upstream
        upstream: "php:http"
